export const incompleteCardsApi = [
    {
        _id:1,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:2,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:3,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:4,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:5,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:6,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
]

export const todoCardsApi = [
    {
        _id:11,
        name:"Client Name 2",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:12,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:13,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:14,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:15,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:16,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
]
export const doingCardsApi = [
    {
        _id:21,
        name:"Client Name 3",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:22,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:23,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:24,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:25,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:26,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
]
export const underReviewCardsApi = [
    {
        _id:31,
        name:"Client Name 4",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:32,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:33,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:34,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:35,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:36,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
]
export const completedCardsApi = [
    {
        _id:41,
        name:"Client Name 5",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:42,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:43,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:44,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:45,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:46,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
]
export const overdueCardsApi = [
    {
        _id:51,
        name:"Client Name 6",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:52,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:53,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:54,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:55,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
    {
        _id:56,
        name:"Client Name",
        friendscount:"12+",
        chat:15,
        date:"30-12-2022",
        username:"Sadik Istiak",
        clientpic:"./assets/images/profile_pic_client.png",
        userpic:"./assets/images/user_pic.png",
        friendcount:12,
        chatcount:15,
        attachmentcount:25,
        datetitle:"30-12-2022"
    },
]